sudo: required
services:
  - docker

before_install:
  - docker build -t bhupendraparihar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhupendraparihar/docker-react npm run test
